name: Security and maintainability
on:
  pull_request:
  push:
    branches: [chore/security-ci-pilot]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  audit:
    uses: loic31000/security-ci/.github/workflows/security-audit.yml@022b74b19fc92d0ce5ad2d08fe87a85446f404e2
    with:
      enforce: false

  audit_strict_validation:
    name: Strict mode validation (expected alerts)
    uses: loic31000/security-ci/.github/workflows/security-audit.yml@022b74b19fc92d0ce5ad2d08fe87a85446f404e2
    with:
      enforce: true
