name: Security strict mode validation
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  audit_strict_validation:
    uses: loic31000/security-ci/.github/workflows/security-audit.yml@dbef68c0b8c7aac2b00087aa5efd5cbe8a0e3c15
    with:
      enforce: true
