name: Security strict mode validation
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  audit_strict_validation:
    uses: loic31000/security-ci/.github/workflows/security-audit.yml@fd8327abcc2589069bc0ab6e32e5c642a0a9707e
    with:
      enforce: true
