name: Security strict mode validation
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  audit_strict_validation:
    uses: loic31000/security-ci/.github/workflows/security-audit.yml@022b74b19fc92d0ce5ad2d08fe87a85446f404e2
    with:
      enforce: true
